### ISSUE TITLE
Access the parent component of the DOM of a child component

### ISSUE THREAD

**Issue by w-jerome** [studiometa/js-toolkit#53]
Hi!

I regularly use the JS toolkit and I noticed a few things.

When you put in `js-toolkit` components, children have access to the "$parent" property. And this component is not its parent linked in the DOM, but the `js-toolkit` parent to the one it is linked to.

Example:
Here I have 2 components "Hero" and "HeroSlider". They can work independently because in my forehead I can create simple Hero and also Hero sliders. If I want it to communicate together I have to go through the "refs".

`index.html`
```html
<html>
  <body>
    <div data-component="HeroSlider">
      <div data-component="Hero" data-ref="heros[]">
        …
      </div>
      <div data-component="Hero" data-ref="heros[]">
        …
      </div>
    </div>
  </body>
</html>
```

`index2.html`
```html
<html>
  <body>
    <div data-component="Hero">
      …
    </div>
  </body>
</html>
```

`app.js`
```js
import Base from '@studiometa/js-toolkit';
import Hero from './components/Hero';
import HeroSlider from './components/HeroSlider';

class App extends Base {
  get config() {
    return {
      name: 'App',
      components: {
        Hero,
        HeroSlider,
      },
    };
  }
}

export default = new App(document.documentElement);
```

`components/Hero.js`
```js
import Base from '@studiometa/js-toolkit';

export default class Hero extends Base {
  get config() {
    return {
      name: 'Hero',
    };
  }

  mounted() {
    console.log(this.$parent); // is "App" component
    console.log(this.myCustomParent); // is "HeroSlider" component dom parent, but async…
  }
}
```

`components/HeroSlider.js`
```js
import Base from '@studiometa/js-toolkit';

export default class HeroSlider extends Base {
  get config() {
    return {
      name: 'HeroSlider',
    };
  }

  mounted() {
    console.log(this.$parent); // is "App" component

    this.$refs.forEach(($hero) => {
      $hero.myCustomParent = this; // Adds a custom property to the children
    });
  }
}
```

In itself it makes sense, but I think it would be interesting if children could also access their parent from the DOM (`$parentDom`?).

**Comment by titouanmathis** [comment]
This seems to be complicated to implement at the moment, as the components are mounted from the top down. This means that if a component is defined in `App`, it will be mounted when `App` is mounted, and it will then mount its children, etc.

It would also be complex to add a `$parentDom` property that resolves correctly because the selector for a component can be changed to a specific selector other than `[data-component="..."]`.

But, it is possible with the current API to achieve what you are trying to do by registering the `Hero` class as a component of the `HeroSlider` one, but with a different name. This way, `App` will not instantiate the components inside `HeroSlider`. 

See this Codepen for a live demo : https://codepen.io/titouanmathis/pen/yLgqBVv?editors=0001.

You will then be able to trigger custom behavior if needed :  

```js
if (this.$parent instanceof HeroSlider) {
  // do something with the parent component
}
```

To avoid complexity in the `Hero` class with conditions (and a cyclic import), I'd rather suggest to use events from the `Hero` class which could be listened by the `HeroSlider` class: 

```js
class Hero extends Base {
  mounted() {
    this.$emit('event', 'foo');
  }
}

class HeroSlider extends Base {
  static config = {
    name: 'HeroSlider',
    components: { Hero },
  }

  onHeroEvent(value) {
    console.log(value); // 'foo'
  }
}
```
