### ISSUE TITLE
Improve the documentation to be elligible for DocSearch

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/js-toolkit#99]
From the answer [DocSearch](https://docsearch.algolia.com/) sent us on our first application:

> We had a look at the link you provided. Your website looks to be in a building stage. We spotted some “lorem ipsum” content OR blank page OR WIP markup. This means that we won't be able to offer you DocSearch yet. 

Some ideas to improve the doc:
- Complete the guide
- Add recipes to the guide
- Add documentation for all the utilities

**Comment by perruche** [comment]
Down to help with this. 
Should we split it into small chunks to be more efficient on the topic ?

**Comment by notjb** [comment]
Hi, i'm proposing the following improvements :

### Guide
- In the `Usage` Section, add an example for the component (how we hook a component on existing markup) (ex: https://stimulus.hotwire.dev/)
- Add a "Core concepts" section (ex: https://github.github.io/catalyst/guide/introduction/)
- Add a "What's next" section at the bottom, listing useful links to get going (ex: https://eslint.org/docs/user-guide/getting-started#next-steps)

### API
- Add examples for each Interface methods
- Add examples for each Instance methods
- Add examples for each Events

### Utils
- Update the broken source links

### Misc
- Add a **Recipes** section, featuring reusable patterns (ex: a carousel)
- Update typos throughout the documentation code (misspelling, english, ...)
**Note :** As of today, the `lorem ipsum`, has only been spotted in the examples which should be non-blocking.

@perruche @titouanmathis can you amend this so that we get a full _todo list_  for the upcoming weeks ?

**Comment by KeziahMoselle** [comment]
Is there any news on this ? @titouanmathis

**Comment by titouanmathis** [comment]
What @notjb said 😛 

More seriously, this seems like a good starting point. I think we should focus on the **Guide** and the **Recipes** (which could be a section in the guide part). 

@KeziahMoselle You can pick a section and open a PR if you are motivated!

**Comment by KeziahMoselle** [comment]
I can take the **API** section if it's good for y'all !
